In [1]:
import numpy as np

In [2]:
arr1=np.array([3,5,6,7,8])
print(arr1)
print(type(arr1))

[3 5 6 7 8]
<class 'numpy.ndarray'>


In [3]:
array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_2d)
print(type(array_2d))





[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [4]:
array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
### dimensssion checking
array_2d.ndim

2

In [6]:
### create a three dimension array

array_3d = np.array([[[1,2,3,]
,[4,5,6]
,[7,8,9]]])

print(array_3d)
array_3d.ndim

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


3

In [21]:
arr_100=np.arange(1,101)
arr_100

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [20]:
array_100=np.arange(1,101)
array_100

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
arr2=np.linspace(1,5,10)
print(arr2)


[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [ ]:
arr_100=np.arange(1,100)
print(arr_100)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [18]:
array_ones=np.ones((8,8),dtype=int)
array_ones

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [17]:
### creating zero s and idenity matrix

array_0=np.zeros((8,8))
array_0


array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
arr_identity=np.eye((8),dtype=int)
arr_identity

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [ ]:
array_3d.shape

(1, 3, 3)

In [ ]:
list1=[1,2,3,4]
list2=[5,6,7,8]
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8]


In [15]:
arr1=np.array([1,3,4])
arr2=np.array([4,6,7])
print(arr1+arr2)

[ 5  9 11]


In [11]:
array1=np.array([[[[[2,3,4,5]]]]])
array1

array([[[[[2, 3, 4, 5]]]]])

In [12]:
array1.shape

(1, 1, 1, 1, 4)

In [13]:
array1=np.array([4,8,9,12])
print(array1+10)

[14 18 19 22]


In [23]:
array1=np.array([4,8,9,12])
print(array1*10)

[ 40  80  90 120]


In [24]:
array1=np.array([4,8,9,12])
print(array1/10)

[0.4 0.8 0.9 1.2]


In [25]:
array1

array([ 4,  8,  9, 12])

In [26]:
array1[1]

np.int64(8)

In [29]:
print(array1[1])

8


In [30]:
array2=np.array([[1,2,3,4],[6,7,8,9],[10,11,12,13]])
array2

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [31]:
print(array2[1,3])

9


In [39]:
print(array2[2,3])

13


In [ ]:
#slicing in numpy array

